# Generated by Django 4.0.5 on 2022-06-16 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_users_create_at_alter_users_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('feedId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/feeds')),
                ('description', models.CharField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('storieId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/stories')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('interactionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('feedId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posts.feeds')),
                ('storieId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posts.stories')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('feedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.feeds')),
            ],
        ),
    ]
