# Generated by Django 4.0.5 on 2022-06-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastName',
        ),
    ]
