# Generated by Django 4.0.5 on 2022-06-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_users_firstname_remove_users_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.FileField(blank=True, upload_to='uploads/profile'),
        ),
    ]
