# Generated by Django 4.0.5 on 2022-06-16 19:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=datetime.datetime(2022, 6, 16, 19, 54, 31, 470510, tzinfo=utc), editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
