# Generated by Django 4.0.5 on 2022-06-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
